html без css и js
OlhaArtemenko/project_portfolio_codecrafters pull request #3
Opened 2024-04-10 12:18 UTC by wamseky

2024-04-10 12:54 UTC, OlhaArtemenko requested changes
1. привіт, гарна робота, але є нюанси
2. тег section замінити на тег footer
3. Текст “Let’s work together" є заголовком секції. Використати тег h2 в одному тегу, виділивші акцентні слова в span
4.  перший імпут - додати type="email", name="email", aria-label="type your email", required, автофокус прибрати
5. тексарія - додати aria-label="type your comment", required

модальне вікно:
1. перший дів - backdrop
2. другий дів - modal window
3. до кнопки закриття вікна додати іконку
4. заголовок h1 замінити на h3

2024-04-10 13:27 UTC, wamseky commented
я сделала правки которые ты сказала

2024-04-10 15:41 UTC, OlhaArtemenko requested changes
![Знімок екрана 2024-04-10 о 18 43 05](https://github.com/OlhaArtemenko/project_portfolio_codecrafters/assets/146447711/35d23081-ac6a-4e74-bfcc-1ebfdaf30697)

2024-04-11 14:31 UTC, OlhaArtemenko approved these changes

2024-04-11 14:32 UTC, merged