Create pullrequests-list.txt
OlhaArtemenko/project_portfolio_codecrafters pull request #4
Opened 2024-04-10 16:03 UTC by Kamisaku13

2024-04-10 17:18 UTC, OlhaArtemenko commented
не розумію, що це таке)

2024-04-10 17:27 UTC, Kamisaku13 commented
Теперь есть всё?

2024-04-10 18:14 UTC, OlhaArtemenko requested changes
1. після секціі огорнути в дів з класом контейнер. секція не має класу container 
2. до тегу секція додати id
3.  заголовок не потрібно огортати в дів ( після хелоу ставимо тег "/br"
4. до  ul з соціальними мережами додай клас
5. текст IG/FB/YT/GH мають бути перед закриттям тегу "а" а не після нього . так само і в імейлі. він має бути перед закриттям тегу
6. media="(min-width:1440px)"
media="(min-width:768px)"
media="(max-width:767px)"
7. в тегу img в кінці не потрібно розміри зображення

2024-04-10 19:21 UTC, OlhaArtemenko commented
сорі
тут зображення фону це background 
його не потрібно додавати через html 
потім одаси через css

2024-04-11 12:53 UTC, Kamisaku13 commented
Изменила

2024-04-11 15:03 UTC, OlhaArtemenko approved these changes

2024-04-11 15:03 UTC, merged