Update-Projects-Container
OlhaArtemenko/project_portfolio_codecrafters pull request #5
Opened 2024-04-10 16:33 UTC by Ma1g

Added 2 HTML codes
I have 2 ways, i think second one is that "thay want" using ul, but still, need to choose what to use.

2024-04-10 16:35 UTC, Ma1g commented
Вибач, на комп'ютері я не вмію писати українською мовою, трохи складно. Хочеш, щоб я перекладав або я пишу англійською, а потім, якщо потрібно, ти перекладаєш?

2024-04-10 17:49 UTC, OlhaArtemenko requested changes
1. після секції йде клас контейнер. для нього вже задані розміри в файлі зі стилями. твої розміри контейнера не потрібно задавати, бо він буде гумовий від 320 до 375px
2. 
![tempImageU2KFor](https://github.com/OlhaArtemenko/project_portfolio_codecrafters/assets/146447711/9d0cd831-afdf-4fa1-a739-64e3d7e224c0)
другий варіант здається твій був краще він зроблений як потрібно по ТЗ
подивись мтруктуру на фото

2024-04-11 16:06 UTC, OlhaArtemenko requested changes
допиши код повністю 
не вистачає 2х слайдів

2024-04-11 16:22 UTC, OlhaArtemenko approved these changes
!

2024-04-11 16:22 UTC, merged